name: cocotb
on:
  push:
    paths:
      - '**/*.v'
      - '**/*.sv'
      - '**/*.vh'
      - '**/*.svh'
      - '**/*.py'
  pull_request:
jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
      has-tests: ${{ steps.gen.outputs.has-tests }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - id: changes
        uses: tj-actions/changed-files@v47
        with:
          matrix: true
      - id: gen
        run: |
          matrix=$(
            jq -nc \
              --argjson files '${{ steps.changes.outputs.all_changed_files }}' \
              --slurpfile tests .github/tests.json \
              '{
                  include:
                    [$files[] | . as $file | $tests[0] | to_entries[] | . as $entry | select($file | startswith($entry.key)) | $entry.value[] | {test: .}] | unique
              }'
          )

          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
          if jq -e '.include | length > 0' <<<"$matrix" >/dev/null; then
            echo "has-tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "has-tests=false" >> "$GITHUB_OUTPUT"
          fi
  test:
    needs: detect
    if: needs.detect.outputs.has-tests == 'true'
    runs-on: ubuntu-latest
    container: ghcr.io/builderdev212/cocotb-runner:latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
    steps:
      - name: Pull Repository
        uses: actions/checkout@v7
      - name: Mark Repository as Safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run Tests
        run: |
          cd verif/cocotb
          bash scripts/test.sh -p ${{ matrix.test }}
      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: ${{ matrix.test }}
          path: verif/cocotb/tests/${{ matrix.test }}/test-results.xml
          reporter: java-junit
      - name: Publish Coverage Summary
        run: |
          python .github/scripts/cov_summary.py \
            "verif/cocotb/tests/${{ matrix.test }}/coverage/coverage_report.yml" \
            >> "$GITHUB_STEP_SUMMARY"
      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: |
            verif/cocotb/tests/${{ matrix.test }}/test-results.xml
            verif/cocotb/tests/${{ matrix.test }}/coverage
